version: '3.8'

services:
  uptime-kuma:
    build: .
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
    environment:
      - B2_ACCOUNT_ID=${B2_ACCOUNT_ID}
      - B2_ACCOUNT_KEY=${B2_ACCOUNT_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
    restart: unless-stopped
